### ISSUE TITLE
[Help]: 在Google colab上运行，到推理这一步出现错误，ModuleNotFoundError: No module named 'torchcrepe'

### ISSUE THREAD

**Issue by Asgardloki233** [svc-develop-team/so-vits-svc#125]
### 请勾选下方的确认框。

- [X] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

win10

### GPU 型号

525.85.12

### Python版本

Python 3.9.16

### PyTorch版本

2.0.0+cu118

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

UVR处理过的vtb直播音频

### 出现问题的环节或执行的命令

推理

### 问题描述

在推理环节出现以下错误
Traceback (most recent call last):
  File "/content/so-vits-svc/inference_main.py", line 11, in <module>
    from inference import infer_tool
  File "/content/so-vits-svc/inference/infer_tool.py", line 20, in <module>
    import utils
  File "/content/so-vits-svc/utils.py", line 20, in <module>
    from modules.crepe import CrepePitchExtractor
  File "/content/so-vits-svc/modules/crepe.py", line 8, in <module>
    import torchcrepe
ModuleNotFoundError: No module named 'torchcrepe'

### 日志

```python
#@title 合成音频（推理）
#@markdown 需要将音频上传到so-vits-svc/raw 文件夹下, 然后设置模型路径、配置文件路径、合成的音频名称

!python inference_main.py -m "logs/44k/G_32000.pth" -c "configs/config.json" -n "live1.wav" -s qq

Traceback (most recent call last):
  File "/content/so-vits-svc/inference_main.py", line 11, in <module>
    from inference import infer_tool
  File "/content/so-vits-svc/inference/infer_tool.py", line 20, in <module>
    import utils
  File "/content/so-vits-svc/utils.py", line 20, in <module>
    from modules.crepe import CrepePitchExtractor
  File "/content/so-vits-svc/modules/crepe.py", line 8, in <module>
    import torchcrepe
ModuleNotFoundError: No module named 'torchcrepe'
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

![e934426a659fb80f44f449e4c51f136](https://user-images.githubusercontent.com/98253974/230118055-a7a21441-b28d-4904-9b5c-85d0b5341e7d.png)

**Comment by ylzz1997** [comment]
需要安装torchcrepe模块，目前该bug已修复
https://colab.research.google.com/drive/1kv-3y2DmZo0uya8pEr1xk7cSB-4e_Pct?usp=sharing

**Comment by NaruseMioShirakana** [comment]
环境没装全你怎么用
