### ISSUE TITLE
[Help]: 每次训练都在 Epoch: 2 [42%], step: 800 的位置报错退出

### ISSUE THREAD

**Issue by AGuanDao** [svc-develop-team/so-vits-svc#126]
### 请勾选下方的确认框。

- [x] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

Windows 10 家庭版

### GPU 型号

NVIDIA GeForce RTX 2060

### Python版本

python3.9.7

### PyTorch版本

2.0.0+cu118

### sovits分支

4.0-v2

### 数据集来源（用于判断数据集质量）

动画原声采集

### 出现问题的环节或执行的命令

训练

### 问题描述

每次训练都在 INFO:44k:Train Epoch: 2 [42%], step: 800, 的位置报错退出

即使把logs/44k文件夹清空重新训练，也是一样在这个位置报错退出

由于显卡是6G显存，config.json中我修改了batch_size，从6改为2 ，"batch_size": 2

### 日志

```python
INFO:44k:Loaded checkpoint './logs\44k\D_0.pth' (iteration 1)
E:\Python\lib\site-packages\torch\functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\SpectralOps.cpp:867.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
E:\Python\lib\site-packages\torch\autograd\__init__.py:200: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [32, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [32, 1, 4], strides() = [4, 4, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:337.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
INFO:44k:Train Epoch: 1 [0%]
INFO:44k:Losses: [1.8350424766540527, 3.087881326675415, 15.519474029541016, 43.46516799926758, 2.739884614944458], step: 0, lr: 0.0001
INFO:44k:Saving model and optimizer state at iteration 1 to ./logs\44k\G_0.pth
INFO:44k:Saving model and optimizer state at iteration 1 to ./logs\44k\D_0.pth
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
INFO:44k:Train Epoch: 1 [35%]
INFO:44k:Losses: [3.2042624950408936, 1.6023280620574951, 4.85037899017334, 24.364368438720703, 1.8815621137619019], step: 200, lr: 0.0001
INFO:44k:Train Epoch: 1 [71%]
INFO:44k:Losses: [2.024649143218994, 2.5297534465789795, 12.023140907287598, 29.055946350097656, 1.7351597547531128], step: 400, lr: 0.0001
INFO:44k:====> Epoch: 1, cost 366.75 s
INFO:44k:Train Epoch: 2 [6%]
INFO:44k:Losses: [1.9109034538269043, 3.0717015266418457, 15.881654739379883, 31.35890769958496, 2.1832027435302734], step: 600, lr: 9.99875e-05
INFO:44k:Train Epoch: 2 [42%]
INFO:44k:Losses: [2.1936745643615723, 2.2962450981140137, 8.9740629196167, 23.723608016967773, 1.4403268098831177], step: 800, lr: 9.99875e-05
Traceback (most recent call last):
  File "E:\1\2\so-vits-svc\train.py", line 315, in <module>
    main()
  File "E:\1\2\so-vits-svc\train.py", line 53, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "E:\Python\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "E:\Python\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "E:\Python\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "E:\Python\lib\site-packages\torch\utils\data\dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "E:\Python\lib\multiprocessing\queues.py", line 114, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Python\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "E:\1\2\so-vits-svc\train.py", line 124, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "E:\1\2\so-vits-svc\train.py", line 245, in train_and_evaluate
    evaluate(hps, net_g, eval_loader, writer_eval)
  File "E:\1\2\so-vits-svc\train.py", line 269, in evaluate
    for batch_idx, items in enumerate(eval_loader):
  File "E:\Python\lib\site-packages\torch\utils\data\dataloader.py", line 634, in __next__
    data = self._next_data()
  File "E:\Python\lib\site-packages\torch\utils\data\dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
  File "E:\Python\lib\site-packages\torch\utils\data\dataloader.py", line 1295, in _get_data
    success, data = self._try_get_data()
  File "E:\Python\lib\site-packages\torch\utils\data\dataloader.py", line 1146, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 18212) exited unexpectedly
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

![image](https://user-images.githubusercontent.com/88699170/230173384-7a320fa6-fe95-4dfa-ae31-cfbb34c7f3fc.png)
![image](https://user-images.githubusercontent.com/88699170/230173457-8af8987d-f113-43fd-891e-755d785b2233.png)

**Comment by TQG1997** [comment]
试一下不修改配置文件

**Comment by AGuanDao** [comment]
> 试一下不修改配置文件

将batch_size恢复到6

提示显存不足报错
`-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "E:\Python\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "E:\1\2\so-vits-svc\train.py", line 124, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "E:\1\2\so-vits-svc\train.py", line 181, in train_and_evaluate
    y_d_hat_r, y_d_hat_g, _, _ = net_d(y, y_hat.detach())
  File "E:\Python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Python\lib\site-packages\torch\nn\parallel\distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "E:\Python\lib\site-packages\torch\nn\parallel\distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "E:\Python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\1\2\so-vits-svc\models.py", line 203, in forward
    y_d_r, fmap_r = d(y)
  File "E:\Python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\1\2\so-vits-svc\models.py", line 150, in forward
    x = l(x)
  File "E:\Python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    result = hook(self, args)
  File "E:\Python\lib\site-packages\torch\nn\utils\weight_norm.py", line 65, in __call__
    setattr(module, self.name, self.compute_weight(module))
  File "E:\Python\lib\site-packages\torch\nn\utils\weight_norm.py", line 25, in compute_weight
    return _weight_norm(v, g, self.dim)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 5.13 GiB already allocated; 0 bytes free; 5.20 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by AGuanDao** [comment]
> 请提供一下dataset文件夹、filelists/val.txt文件内容的截图，可能是eval环节出了问题，我怀疑可能是valid_loader读不到数据了

谢谢，发现是读不到数据的原因。重启电脑后，可正常运行了，疑似某些文件被系统锁定。

问题解决，准备关闭issue了

**Comment by huangwu5717** [comment]
我也遇到这个问题了，没找到解决办法
