### ISSUE TITLE
[Help]: 推理的时候出现 CUDA out of memory 

### ISSUE THREAD

**Issue by KOUymA** [svc-develop-team/so-vits-svc#157]
### 请勾选下方的确认框。

- [X] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

Linux autodl-container-a7d611913c-9ea361e1 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### GPU 型号

A5000

### Python版本

Python 3.8.16

### PyTorch版本

1.13.1

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

UVR处理过的vtb直播音频

### 出现问题的环节或执行的命令

python inference_main.py -m "logs/44k/G_15200.pth" -c "configs/config.json" -n "Million_Reasons.wav" -t 0 -s "speaker0"

### 问题描述

推理的时候出现显存不足的问题
![image](https://user-images.githubusercontent.com/72074577/232190365-19509346-0dd4-4eca-8e2d-3fb730394520.png)

### 日志

```python
Traceback (most recent call last):
  File "inference_main.py", line 137, in <module>
    main()
  File "inference_main.py", line 111, in main
    out_audio, out_sr = svc_model.infer(spk, tran, raw_path,
  File "/root/miniconda3/so-vits-svc/inference/infer_tool.py", line 208, in infer
    audio = self.net_g_ms.infer(c, f0=f0, g=sid, uv=uv, predict_f0=auto_predict_f0, noice_scale=noice_scale)[0,0].data.float()
  File "/root/miniconda3/so-vits-svc/models.py", line 417, in infer
    z_p, m_p, logs_p, c_mask = self.enc_p(x, x_mask, f0=f0_to_coarse(f0), noice_scale=noice_scale)
  File "/root/miniconda3/envs/sovits/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/so-vits-svc/models.py", line 114, in forward
    x = self.enc_(x * x_mask, x_mask)
  File "/root/miniconda3/envs/sovits/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/so-vits-svc/modules/attentions.py", line 85, in forward
    y = self.attn_layers[i](x, x, attn_mask)
  File "/root/miniconda3/envs/sovits/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/so-vits-svc/modules/attentions.py", line 189, in forward
    x, self.attn = self.attention(q, k, v, mask=attn_mask)
  File "/root/miniconda3/so-vits-svc/modules/attentions.py", line 221, in attention
    relative_weights = self._absolute_position_to_relative_position(p_attn)
  File "/root/miniconda3/so-vits-svc/modules/attentions.py", line 287, in _absolute_position_to_relative_position
    x_flat = F.pad(x_flat, commons.convert_pad_shape([[0, 0], [0, 0], [length, 0]]))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.26 GiB (GPU 0; 23.69 GiB total capacity; 18.89 GiB already allocated; 3.20 GiB free; 19.19 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

![image](https://user-images.githubusercontent.com/72074577/232190375-ae54accf-283d-4772-9049-4b478a8705c4.png)

**Comment by ylzz1997** [comment]
设置下自动切片，记得把交叉淡入时间也设置一下

**Comment by HuanLinOTO** [comment]
it's look lite a problem of using, concert to discussion
