### ISSUE TITLE
安装依赖包fairseq失败

### ISSUE THREAD

**Issue by vivagwb** [svc-develop-team/so-vits-svc#159]
### 请勾选下方的确认框。

- [X] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

winver 22H2

### GPU 型号

i5-8400

### Python版本

3.9.10

### PyTorch版本

1.13.1+cu116

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

歌手MP3歌曲

### 出现问题的环节或执行的命令

python preprocess_hubert_f0.py

### 问题描述

python preprocess_hubert_f0.py   执行后报错ModuleNotFoundError: No module named 'fairseq'
安装fairseq，执行pip install --editable ./  
报错如下离职

### 日志

```python
PS  pip install --editable ./
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///G:/Learn/AmateurLearning/AI/Practice/fairseq
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6'
      Traceback (most recent call last):
        File "F:\Python3.9\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "F:\Python3.9\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "F:\Python3.9\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "C:\Users\gwb19\AppData\Local\Temp\pip-build-env-l10b6mru\overlay\Lib\site-packages\setuptools\build_meta.py", line 447, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "C:\Users\gwb19\AppData\Local\Temp\pip-build-env-l10b6mru\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel   
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\gwb19\AppData\Local\Temp\pip-build-env-l10b6mru\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\gwb19\AppData\Local\Temp\pip-build-env-l10b6mru\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 246, in <module>
      OSError: [WinError 1314] 客户端没有所需的特权。: '..\\examples' -> 'fairseq\\examples'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

![image](https://user-images.githubusercontent.com/14922541/232210529-e5843633-95fe-48e6-8c09-b773643326ae.png)
![image](https://user-images.githubusercontent.com/14922541/232210542-14b8c5e9-816a-4a47-a039-fca442b00e2a.png)

**Comment by vivagwb** [comment]
有没有大佬遇到同样的问题？

**Comment by ylzz1997** [comment]
以管理员身份运行并执行命令

**Comment by vivagwb** [comment]
> 以管理员身份运行并执行命令
又出现新问题。。。

**Comment by Miuzarte** [comment]
> > 以管理员身份运行并执行命令
> 
> 又出现新问题。。。

日志
