### ISSUE TITLE
[Help]: 推理时音频文件报错

### ISSUE THREAD

**Issue by bilbillm** [svc-develop-team/so-vits-svc#163]
### 请勾选下方的确认框。

- [X] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

colab平台

### GPU 型号

Tesla T4

### Python版本

python3.8.9

### PyTorch版本

1.13.1+cu117

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

纯人声语音

### 出现问题的环节或执行的命令

Start inference (and download)

### 问题描述

下载时无法找到文件，应该是上半部分报错的问题，是speaker设置错了吗？
![2、](https://user-images.githubusercontent.com/60431233/232266406-4d5d6d6b-c59f-4ade-ac16-0b2bc86a3a43.jpg)
![1](https://user-images.githubusercontent.com/60431233/232266409-cb53da7f-8f68-4a14-96fa-bf0d43f75af5.png)

### 日志

```python
load model(s) from hubert/checkpoint_best_legacy_500.pt
INFO:fairseq.tasks.hubert_pretraining:current directory is /content/so-vits-svc
INFO:fairseq.tasks.hubert_pretraining:HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
INFO:fairseq.models.hubert.hubert:HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
load 
INFO:root:Loaded checkpoint '/content/so-vits-svc/logs/44k/G_6400.pth' (iteration 427)
#=====segment start, 22.513s======
Traceback (most recent call last):
  File "/content/so-vits-svc/inference_main.py", line 137, in <module>
    main()
  File "/content/so-vits-svc/inference_main.py", line 111, in main
    out_audio, out_sr = svc_model.infer(spk, tran, raw_path,
  File "/content/so-vits-svc/inference/infer_tool.py", line 203, in infer
    sid = torch.LongTensor([int(speaker_id)]).to(self.dev).unsqueeze(0)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-10-2816dd7a51a9> in <cell line: 34>()
     34 if download_after_inference:
     35   from google.colab import files
---> 36   files.download(wav_output)

/usr/local/lib/python3.9/dist-packages/google/colab/files.py in download(filename)
    220   if not _os.path.exists(filename):
    221     msg = 'Cannot find file: {}'.format(filename)
--> 222     raise FileNotFoundError(msg)  # pylint: disable=undefined-variable
    223 
    224   comm_manager = _IPython.get_ipython().kernel.comm_manager

FileNotFoundError: Cannot find file: /content/so-vits-svc/results/001.wav_0key_angelina.flac
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

![3](https://user-images.githubusercontent.com/60431233/232266411-131c1be4-fc65-40c7-8511-8867340a065a.jpg)
![5](https://user-images.githubusercontent.com/60431233/232266439-7f27319e-524d-4873-aadf-366cad27c82a.jpg)
![4](https://user-images.githubusercontent.com/60431233/232266441-c592ef51-0d38-4f2c-b34c-8ead6587a43c.jpg)

**Comment by Miuzarte** [comment]
colab现在暂时推理不了，修不明白

**Comment by Miuzarte** [comment]
临时写了个本地环境搭建教程
[https://github.com/svc-develop-team/so-vits-svc/wiki/简单本地环境搭建和推理](https://github.com/svc-develop-team/so-vits-svc/wiki/%E7%AE%80%E5%8D%95%E6%9C%AC%E5%9C%B0%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA%E5%92%8C%E6%8E%A8%E7%90%86)

**Comment by Miuzarte** [comment]
修好了的
