### ISSUE TITLE
ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 88, got 96

### ISSUE THREAD

**Issue by Irving-ren** [svc-develop-team/so-vits-svc#24]
Great work!  This error occurred when extracting Hubert and f0 features. Is there any misusing part about `hubert/checkpoint_best_legacy_500.pt`? That was downloaded from `http://obs.cstcloud.cn/share/obs/sankagenkeshi/checkpoint_best_legacy_500.pt` 
BTW, I was under the 4.0 version with python3.8. Thanks for your information

_Traceback (most recent call last):
  File "/home/mike/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/mike/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/sdb/mike/repo/so-vits-svc/preprocess_hubert_f0.py", line 44, in process_batch
    process_one(filename, hmodel)
  File "/data/sdb/mike/repo/so-vits-svc/preprocess_hubert_f0.py", line 34, in process_one
    f0 = utils.compute_f0_dio(wav, sampling_rate=sampling_rate, hop_length=hop_length)
  File "/data/sdb/mike/repo/so-vits-svc/utils.py", line 156, in compute_f0_dio
    import pyworld
  File "/home/mike/anaconda3/envs/sovits/lib/python3.8/site-packages/pyworld/__init__.py", line 7, in <module>
    from .pyworld import *
  File "__init__.pxd", line 199, in init pyworld.pyworld
ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 88, got 96_

**Comment by Irving-ren** [comment]
Thanks, It works like a charm!

**Comment by Cuieney** [comment]
thx, macos m1 It's up and running
