### ISSUE TITLE
Colab inference not working at all

### ISSUE THREAD

**Issue by marcswig** [svc-develop-team/so-vits-svc#26]
Whenever I try to use inference at the last inference step, it says this:

Traceback (most recent call last):  File "/content/so-vits-svc/inference_main.py", line 101, in <module>    main()  File "/content/so-vits-svc/inference_main.py", line 47, in main    svc_model = Svc(args.model_path, args.config_path, args.device, args.cluster_model_path)  File "/content/so-vits-svc/inference/infer_tool.py", line 127, in __init__    self.load_model()  File "/content/so-vits-svc/inference/infer_tool.py", line 138, in load_model    self.hps_ms.data.filter_length // 2 + 1,AttributeError: 'HParams' object has no attribute 'filter_length'

Any fix?
![image_2023-03-14_212606368](https://user-images.githubusercontent.com/127893805/225128176-2c3bdaf0-ea02-4ba7-ba4a-65b94efb09b2.png)

**Comment by Miuzarte** [comment]
Which branch is this?

**Comment by seq2193** [comment]
這好像不是此github 的colab 筆記本?
