### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by Irving-ren** [svc-develop-team/so-vits-svc#29]
Hi, the error occurred when extracting the spectrogram. The error is caused by loading the empty *spec.pt file, which was interrupting the training process. 

Env: ubuntu/python3.8/branch 4.0
Stage: Training. The Hubert and f0 features were extracted before the training stage.

> Traceback (most recent call last):
  File "/home/mike/anaconda3/envs/sovits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/data/sdb/mike/repo/so-vits-svc/train.py", line 122, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "/data/sdb/mike/repo/so-vits-svc/train.py", line 141, in train_and_evaluate
    for batch_idx, items in enumerate(train_loader):
  File "/home/mike/anaconda3/envs/sovits/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/mike/anaconda3/envs/sovits/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1313, in _next_data
    return self._process_data(data)
  File "/home/mike/anaconda3/envs/sovits/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/mike/anaconda3/envs/sovits/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
EOFError: Caught EOFError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/home/mike/anaconda3/envs/sovits/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mike/anaconda3/envs/sovits/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mike/anaconda3/envs/sovits/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/sdb/mike/repo/so-vits-svc/data_utils.py", line 90, in __getitem__
    return self.get_audio(self.audiopaths[index][0])
  File "/data/sdb/mike/repo/so-vits-svc/data_utils.py", line 53, in get_audio
    spec = torch.load(spec_filename)
  File "/home/mike/anaconda3/envs/sovits/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/mike/anaconda3/envs/sovits/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by NaruseMioShirakana** [comment]
This is a residual BUG in Vits. A common BUG in multithreaded IO. (Only appears during multi-GPU training)
The DataLoader method of SoVits is the same as that of Vits in that the spec file is generated by thread 0 at the time of the first Epoch. If it detects that the spec file already exists, it directly reads from the existing spec file. This leads to a BUG: If two or more different threads extract the same data in the dataset at the time of Epoch 1, thread 0 generates a file (but not yet written), and other threads read the file directly because they detect that the file already exists. At this time, because the file is not yet written, So It got EOF (End Of File), EOFError raised.
The way to solve this problem is to start with a single GPU Epoch and then switch to multiple Gpus

**Comment by Irving-ren** [comment]
Thanks for your information. I got it and successfully trained with a single GPU for now.
