### ISSUE TITLE
推理时出现 INFO:root:Loaded checkpoint 后卡住

### ISSUE THREAD

**Issue by Yan233th** [svc-develop-team/so-vits-svc#3]
看了看报错信息，好像是模型不匹配，能改模型信息吗，或者符合的模型在哪里可以找到
训练好的模型是在网上找到，但是我换了三四个模型都是报这个错

```DEBUG:matplotlib.pyplot:Loaded backend agg version v2.2.
INFO:root:enc_p_.pre.weight is not in the checkpoint
INFO:root:enc_p_.pre.bias is not in the checkpoint     
INFO:root:enc_p_.proj.weight is not in the checkpoint  
INFO:root:enc_p_.proj.bias is not in the checkpoint    
INFO:root:enc_p_.f0_emb.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.0.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.0.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.0.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.0.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.0.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.0.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.0.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.0.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.0.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.0.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.1.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.1.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.1.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.1.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.1.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.1.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.1.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.1.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.1.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.1.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.2.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.2.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.2.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.2.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.2.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.2.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.2.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.2.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.2.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.2.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.3.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.3.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.3.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.3.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.3.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.3.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.3.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.3.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.3.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.3.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.4.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.4.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.4.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.4.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.4.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.4.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.4.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.4.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.4.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.4.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.5.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.5.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.5.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.5.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.5.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.5.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.5.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.5.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.5.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.5.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.6.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.6.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.6.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.6.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.6.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.6.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.6.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.6.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.6.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.6.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.7.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.7.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.7.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.7.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.7.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.7.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.7.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.7.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.7.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.7.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.8.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.8.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.8.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.8.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.8.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.8.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.8.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.8.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.8.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.8.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.9.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.9.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.9.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.9.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.9.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.9.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.9.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.9.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.9.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.9.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.10.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.10.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.10.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.10.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.10.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.10.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.10.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.10.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.10.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.10.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.11.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.11.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.11.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.11.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.11.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.11.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.11.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.11.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.11.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.11.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.12.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.12.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.12.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.12.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.12.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.12.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.12.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.12.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.12.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.12.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.13.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.13.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.13.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.13.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.13.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.13.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.13.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.13.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.13.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.13.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.14.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.14.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.14.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.14.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.14.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.14.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.14.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.14.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.14.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.14.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.15.emb_rel_k is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.15.emb_rel_v is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.15.conv_q.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.15.conv_q.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.15.conv_k.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.15.conv_k.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.15.conv_v.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.15.conv_v.bias is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.15.conv_o.weight is not in the checkpoint
INFO:root:enc_p_.enc_.attn_layers.15.conv_o.bias is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.0.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.0.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.1.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.1.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.2.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.2.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.3.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.3.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.4.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.4.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.5.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.5.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.6.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.6.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.7.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.7.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.8.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.8.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.9.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.9.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.10.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.10.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.11.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.11.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.12.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.12.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.13.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.13.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.14.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.14.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.15.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_1.15.beta is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.0.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.0.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.0.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.0.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.1.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.1.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.1.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.1.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.2.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.2.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.2.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.2.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.3.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.3.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.3.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.3.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.4.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.4.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.4.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.4.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.5.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.5.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.5.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.5.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.6.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.6.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.6.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.6.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.7.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.7.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.7.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.7.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.8.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.8.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.8.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.8.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.9.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.9.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.9.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.9.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.10.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.10.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.10.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.10.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.11.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.11.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.11.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.11.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.12.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.12.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.12.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.12.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.13.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.13.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.13.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.13.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.14.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.14.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.14.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.14.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.15.conv_1.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.15.conv_1.bias is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.15.conv_2.weight is not in the checkpoint
INFO:root:enc_p_.enc_.ffn_layers.15.conv_2.bias is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.0.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.0.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.1.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.1.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.2.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.2.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.3.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.3.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.4.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.4.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.5.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.5.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.6.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.6.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.7.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.7.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.8.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.8.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.9.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.9.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.10.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.10.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.11.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.11.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.12.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.12.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.13.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.13.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.14.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.14.beta is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.15.gamma is not in the checkpoint
INFO:root:enc_p_.enc_.norm_layers_2.15.beta is not in the checkpoint
Traceback (most recent call last):
  File "d:\114514\Program Files\so-vits-svc\inference_main.py", line 19, in <module>
    svc_model = Svc(model_path, config_path)
  File "d:\114514\Program Files\so-vits-svc\inference\infer_tool.py", line 166, in __init__
    self.load_model()
  File "d:\114514\Program Files\so-vits-svc\inference\infer_tool.py", line 184, in load_model
    _ = utils.load_checkpoint(self.net_g_path, self.net_g_ms, None)
  File "d:\114514\Program Files\so-vits-svc\utils.py", line 114, in load_checkpoint
    model.load_state_dict(new_state_dict)
  File "C:\ProgramData\Miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for dec.noise_convs.0.weight: copying a param with shape torch.Size([256, 1, 128]) from checkpoint, the shape in current model is torch.Size([256, 1, 64]).
        size mismatch for dec.noise_convs.1.weight: copying a param with shape torch.Size([128, 1, 16]) from checkpoint, the shape in current model is torch.Size([128, 1, 8]).
        size mismatch for dec.noise_convs.2.weight: copying a param with shape torch.Size([64, 1, 8]) from checkpoint, the shape in current model is torch.Size([64, 1, 4]).
        size mismatch for dec.noise_convs.3.weight: copying a param with shape torch.Size([32, 1, 4]) from checkpoint, the shape in current model is torch.Size([32, 1, 1]).
        size mismatch for dec.conv_post.weight_v: copying a param with shape torch.Size([1, 16, 7]) from checkpoint, the shape in current model is torch.Size([1, 32, 7]).```

**Comment by ylzz1997** [comment]
你是不是sovits3.0的模型放4.0里面去了？

**Comment by Yan233th** [comment]
> 你是不是sovits3.0的模型放4.0里面去了？

不是，模型都是4.0的

**Comment by Yan233th** [comment]
破案了，我git clone的时候没注意，一直跑在32k分支上，但我给的是4.0的模型😶，以及hubert不是4.0的，所以会有模型对不上的情况出现
现在我又有了个新的问题：在我开始执行推理py后，在提示`INFO:root:Loaded checkpoint 'logs/44k/teio.pth' (iteration 201)`后就一直卡在这 (3s的音频等了两三个小时了都) ，之后没有任何输出信息，但是一直占用着我的一个cpu线程，硬盘和显卡也没有占用，把所有的`torch.device`都设置成`"cuda"`后依然如此，很奇怪
