### ISSUE TITLE
dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by quicksandznzn** [svc-develop-team/so-vits-svc#323]
python 3.8
torch 2.0.1

Traceback (most recent call last):
  File "/home/app/miniconda3/envs/so-vits-svc-4.1/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 48, in <module>
    from ._check_build import check_build  # noqa
ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference_main.py", line 5, in <module>
    from inference import infer_tool
  File "/data1/develop/zhangshuai/so-vits-svc/inference/infer_tool.py", line 11, in <module>
    import librosa
  File "/home/app/miniconda3/envs/so-vits-svc-4.1/lib/python3.8/site-packages/librosa/__init__.py", line 211, in <module>
    from . import decompose
  File "/home/app/miniconda3/envs/so-vits-svc-4.1/lib/python3.8/site-packages/librosa/decompose.py", line 19, in <module>
    import sklearn.decomposition
  File "/home/app/miniconda3/envs/so-vits-svc-4.1/lib/python3.8/site-packages/sklearn/__init__.py", line 81, in <module>
    from . import __check_build  # noqa: F401
  File "/home/app/miniconda3/envs/so-vits-svc-4.1/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 50, in <module>
    raise_build_error(e)
  File "/home/app/miniconda3/envs/so-vits-svc-4.1/lib/python3.8/site-packages/sklearn/__check_build/__init__.py", line 31, in raise_build_error
    raise ImportError(
ImportError: dlopen: cannot load any more object with static TLS
___________________________________________________________________________
Contents of /home/app/miniconda3/envs/so-vits-svc-4.1/lib/python3.8/site-packages/sklearn/__check_build:
setup.py                  __init__.py               _check_build.cpython-38-x86_64-linux-gnu.so
__pycache__
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.

**Comment by HuanLinOTO** [comment]
If you have already searched on Google or Bing, then you should know how to solve this problem.
Here is my solution:
```
export LD_PRELOAD=/path/to/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0
```
