### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 729533572** [svc-develop-team/so-vits-svc#324]
### 系统平台版本号

windows 11

### GPU 型号

4090

### Python版本

3.10

### PyTorch版本

n/a

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

个人声音处理

### 出现问题的环节或执行的命令

推理

### 情况描述

训练2400步后，生成的模型，在预处理的时候报错
异常信息:Given groups=1, weight of size [192, 768, 5], expected input[1, 256, 773] to have 768 channels, but got 256 channels instead
请排障后重试

### 日志

```python
Traceback (most recent call last):
  File "app.py", line 150, in vc_fn
    _audio = model.slice_inference(temp_path, sid, vc_transform, slice_db, cluster_ratio, auto_f0, noise_scale,pad_seconds,cl_num,lg_num,lgr_num,F0_mean_pooling,enhancer_adaptive_key,cr_threshold)
  File "/root/so-vits-svc4/inference/infer_tool.py", line 285, in slice_inference
    out_audio, out_sr = self.infer(spk, tran, raw_path,
  File "/root/so-vits-svc4/inference/infer_tool.py", line 210, in infer
    audio = self.net_g_ms.infer(c, f0=f0, g=sid, uv=uv, predict_f0=auto_predict_f0, noice_scale=noice_scale)[0,0].data.float()
  File "/root/so-vits-svc4/models.py", line 409, in infer
    x = self.pre(c) * x_mask + self.emb_uv(uv.long()).transpose(1,2)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [192, 768, 5], expected input[1, 256, 773] to have 768 channels, but got 256 channels instead
```

**Comment by Stardust-minus** [comment]
应该是配置文件错误，请使用vev768l12的配置文件

**Comment by HuanLinOTO** [comment]
4.1 和 4.0 不兼容，不是开发问题不要用 issues 询问
