### ISSUE TITLE
[Help]: 是否有支持VITS模型ONNX的计划？

### ISSUE THREAD

**Issue by gandolfxu** [svc-develop-team/so-vits-svc#341]
### 请勾选下方的确认框。

- [X] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

Ubuntu 18.04

### GPU 型号

V100 32G

### Python版本

3.9.13

### PyTorch版本

1.12.1

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

内部TTS数据

### 出现问题的环节或执行的命令

推理：python inference_main.py

### 问题描述

已经使用[onnx_export.py](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/onnx_export.py)将模型（G_*.pth）转换为onnx格式。如何在推理阶段加载该onnx模型？

执行命令：
python inference_main.py \
    -m "checkpoints/*/G_53600.onnx" \
    -c "logs/44k/config_onnx.json" \
    -s * -n $audio_files -t 0 \
    --f0_predictor pm \

### 日志

```python
Traceback (most recent call last):
  File "/home/notebook/code/personal/so-vits-svc/inference_main.py", line 164, in <module>
    main()
  File "/home/notebook/code/personal/so-vits-svc/inference_main.py", line 95, in main
    svc_model = Svc(args.model_path,
  File "/home/notebook/code/personal/so-vits-svc/inference/infer_tool.py", line 164, in __init__
    self.load_model(spk_mix_enable)
  File "/home/notebook/code/personal/so-vits-svc/inference/infer_tool.py", line 194, in load_model
    _ = utils.load_checkpoint(self.net_g_path, self.net_g_ms, None)
  File "/home/notebook/code/personal/so-vits-svc/utils.py", line 153, in load_checkpoint
    checkpoint_dict = torch.load(checkpoint_path, map_location='cpu')
  File "/home/notebook/code/personal/so-vits-svc/.venv/lib/python3.9/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/notebook/code/personal/so-vits-svc/.venv/lib/python3.9/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x08'.
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

不涉及

**Comment by ylzz1997** [comment]
加载onnx模型需要使用另一个项目，请参考[MoeVoiceStudio](https://github.com/NaruseMioShirakana/MoeVoiceStudio)
