### ISSUE TITLE
训练过程报错_pickle.UnpicklingError

### ISSUE THREAD

**Issue by Yuxiza** [svc-develop-team/so-vits-svc#46]
**系统平台**: CentOS 7.9
**出现问题的环节**: 训练
**Python版本**:  3.8.13
**PyTorch版本**:  Version: 1.13.1+cu116
**所用分支**: 4.0-v2
**所用数据集**: 本人
授权证明截图:

**问题描述**: 训练开始后报错，无法继续，报错如下，网络搜索得到的结果是与torch版本有关，但在我跟换了torch版本之后似乎也没有改变。可能是由于torch.load()引起。

**日志**:
在slurm环境中使用srun运行 4卡
前面都是正常的...
（部分文件夹涉及隐私用星号代替了）
```
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
INFO:44k:Train Epoch: 1 [0%]
INFO:44k:Losses: [4.583632469177246, 2.16941237449646, 11.800090789794922, 124.89070129394531, 616.9237060546875], step: 0, lr: 0.0002
/home/****/project/conda_envs/sov/lib/python3.8/site-packages/torch/autograd/__init__.py:197: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [32, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [32, 1, 4], strides() = [4, 4, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:325.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
INFO:44k:Saving model and optimizer state at iteration 1 to ./logs/44k/G_0.pth
INFO:44k:Saving model and optimizer state at iteration 1 to ./logs/44k/D_0.pth
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
/home/****/project/conda_envs/sov/lib/python3.8/site-packages/torch/autograd/__init__.py:197: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [32, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [32, 1, 4], strides() = [4, 4, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:325.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "train.py", line 310, in <module>
    main()
  File "train.py", line 51, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/home/****/project/conda_envs/sov/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/****/project/conda_envs/sov/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/****/project/conda_envs/sov/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home/****/project/conda_envs/sov/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/scratch/****/so-vits-svc/train.py", line 122, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "/scratch/****/so-vits-svc/train.py", line 141, in train_and_evaluate
    for batch_idx, items in enumerate(train_loader):
  File "/home/****/project/conda_envs/sov/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/****/project/conda_envs/sov/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/home/****/project/conda_envs/sov/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/****/project/conda_envs/sov/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
_pickle.UnpicklingError: Caught UnpicklingError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/****/project/conda_envs/sov/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/****/project/conda_envs/sov/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/****/project/conda_envs/sov/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/scratch/****/so-vits-svc/data_utils.py", line 88, in __getitem__
    return self.get_audio(self.audiopaths[index][0])
  File "/scratch/****/so-vits-svc/data_utils.py", line 51, in get_audio
    spec = torch.load(spec_filename)
  File "/home/****/project/conda_envs/sov/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/****/project/conda_envs/sov/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```
之后就exit code 1了
同样的数据集在windows平台也尝试过，没有报错。

**Comment by Yuxiza** [comment]
我感觉似乎是由于并行化导致的，因为多次尝试都是在process 2 报错，参见https://github.com/koomri/text-segmentation/issues/1

**Comment by Yuxiza** [comment]
在神奇的重装了几次numpy并又重新处理了一下数据之后这个问题莫名的消失了_(:з」∠)_ 新的问题变成了训练速度似乎过于的慢。。。

**Comment by HuanLinOTO** [comment]
你是不是在用 cpu 训练

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by HuanLinOTO** [comment]
shot

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Yuxiza** [comment]
> 你是不是在用 cpu 训练
> 
> Generated by [koishi-plugin-github](https://github.koishi.chat/).

那倒没有，不过之前gpu看功率确实跑不太满。现在在给numpy降了个级之后似乎有所好转。现在显卡功耗在2/3到3/4左右。。。虽然还是感觉有点慢。6个G的dataset跑一个epoch265秒算是慢吗。

**Comment by HuanLinOTO** [comment]
什么显卡呢，看看显存占用 
```sh
nvidia-smi
```

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Yuxiza** [comment]
<img width="437" alt="1679153021543" src="https://user-images.githubusercontent.com/87649577/226114967-d3fb5fdf-68dc-4df0-b79e-a19c61e1fe7a.png">

**Comment by HuanLinOTO** [comment]
哇。。。富哥
训练前打碎音频了么 可以尝试切碎后调大点bs
另外你的训练数据有多少啊

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Yuxiza** [comment]
倒也不是富哥qwq 主要是现在有组织qwq
已经切碎了，现在bs调的小是因为debug
我觉得慢主要是因为同样的参数在隔壁真富哥的4090上一个epoch是70多秒
 训练数据的话大概能有4-5小时？ （能整出来这么多自己的音频还得感谢以前的缺de老师

**Comment by HuanLinOTO** [comment]
我本人只用过一次sovits。。。 炼了3.4版本原神的几个人物，一张V100的训练速度大概也是180s左右，我觉得是不是你硬盘和内存的问题，读写拉满了，内存不够放？

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by NaruseMioShirakana** [comment]
看起来这是一个load已经生成的spec文件时出现的错误。
.pt文件本质上是一个压缩包，而这个压缩包之中的文件是序列化的torch实例（类似于Json），载入.pt文件相当于反序列化这个文件中的内容，这里的pickle就是执行这个序列化和反序列化的过程，不过pickle的序列化和反序列化与json不同，json使用了文本文件形式，而pickle使用了二进制形式，读写二进制形式的文件，受到其读取和写入方法的影响较大，所以很有可能是相关模块多个版本之间load函数不一致，而你是用的版本与之不匹配。

**Comment by Yuxiza** [comment]
查了一下存储服务器的盘是SAS的。。。4kIO应该是到头了所以速度慢。结案了。。。
