### ISSUE TITLE
我必须要吐槽一下，为什么readme完全没有给出环境要求？？？？当然我白嫖还说这种话有点不应该，但确实是个问题。requirement经常找不到对应版本

### ISSUE THREAD

**Issue by majisama** [svc-develop-team/so-vits-svc#57]

**Comment by Miuzarte** [comment]
python3.8 3.9装了requirement都能跑，你找不到对应版本第一时间不应该是百度怎么回事吗？难道这项目出来这么久就你发现requirement.txt有bug？

**Comment by Miuzarte** [comment]
用官方pip源没那么多事

**Comment by NaruseMioShirakana** [comment]
你conda一个新环境或者是pip一个venv直接装requirements不就行了吗

**Comment by NaruseMioShirakana** [comment]
requirement经常找不到对应版本并不是requirements有误，而是requirements指出的依赖版本与你python环境现有的某些库有冲突

**Comment by majisama** [comment]
> 

是的，就是因为python版本不明确所导致的，所以我才吐槽应该标注版本

**Comment by majisama** [comment]
> requirement经常找不到对应版本并不是requirements有误，而是requirements指出的依赖版本与你python环境现有的某些库有冲突

是的，就是因为python版本不明确所导致的，所以我才吐槽应该标注版本

**Comment by majisama** [comment]
> python3.8 3.9装了requirement都能跑，你找不到对应版本第一时间不应该是百度怎么回事吗？难道这项目出来这么久就你发现requirement.txt有bug？

有时候这么多库其中某些可能会在不同的python版本中出现不可预测的兼容性问题，所以标注一下其实是最好的，我测试是3.6。现在3.8可以用了

**Comment by Kylin93CN** [comment]
3.9没跑成功， 有onnx的问题，现在用的3.8

**Comment by owancato** [comment]
目前實測下來 在windows10底下 用python3.8基本上不會出問題

**Comment by dragonyjd** [comment]
我就是UBUNTU18环境 ，用的conda create -n sovits python=3.8    pip install -r require.txt，报的各种numpy错误，改成其他 版本也过不了
  File "pyworld/pyworld.pyx", line 6, in init pyworld.pyworld
  File "__init__.pxd", line 945, in numpy.import_array
ImportError: numpy.core.multiarray failed to import

**Comment by Miuzarte** [comment]
> 我就是UBUNTU18环境 ，用的conda create -n sovits python=3.8 pip install -r require.txt，报的各种numpy错误，改成其他 版本也过不了 File "pyworld/pyworld.pyx", line 6, in init pyworld.pyworld File "**init**.pxd", line 945, in numpy.import_array ImportError: numpy.core.multiarray failed to import

日志发完整，我只能怀疑是不是没有conda activate

**Comment by dragonyjd** [comment]
> 

这点常识还是有的，肯定conda activate了

 python preprocess_hubert_f0.py
[22]
Loading hubert for content...
load model(s) from hubert/checkpoint_best_legacy_500.pt
INFO:fairseq.tasks.hubert_pretraining:current directory is /data/home/gxl/so-vits-svc
INFO:fairseq.tasks.hubert_pretraining:HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
INFO:fairseq.models.hubert.hubert:HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False}
Loaded hubert.
  0%|                                                                                                                              | 0/22 [00:03<?, ?it/s]
Process Process-1:
Traceback (most recent call last):
  File "__init__.pxd", line 943, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/gxl/so-vits-svc/preprocess_hubert_f0.py", line 44, in process_batch
    process_one(filename, hmodel)
  File "/data/home/gxl/so-vits-svc/preprocess_hubert_f0.py", line 34, in process_one
    f0 = utils.compute_f0_dio(wav, sampling_rate=sampling_rate, hop_length=hop_length)
  File "/data/home/gxl/so-vits-svc/utils.py", line 156, in compute_f0_dio
    import pyworld
  File "/data/anaconda3/envs/sovits/lib/python3.8/site-packages/pyworld/__init__.py", line 7, in <module>
    from .pyworld import *
  File "pyworld/pyworld.pyx", line 6, in init pyworld.pyworld
  File "__init__.pxd", line 945, in numpy.import_array
ImportError: numpy.core.multiarray failed to import

**Comment by Miuzarte** [comment]
> > 
> 
> 这点常识还是有的，肯定conda activate了
> 
> python preprocess_hubert_f0.py [22] Loading hubert for content... load model(s) from hubert/checkpoint_best_legacy_500.pt INFO:fairseq.tasks.hubert_pretraining:current directory is /data/home/gxl/so-vits-svc INFO:fairseq.tasks.hubert_pretraining:HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False} INFO:fairseq.models.hubert.hubert:HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False} Loaded hubert. 0%| | 0/22 [00:03<?, ?it/s] Process Process-1: Traceback (most recent call last): File "**init**.pxd", line 943, in numpy.import_array RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/data/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/data/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/data/home/gxl/so-vits-svc/preprocess_hubert_f0.py", line 44, in process_batch process_one(filename, hmodel) File "/data/home/gxl/so-vits-svc/preprocess_hubert_f0.py", line 34, in process_one f0 = utils.compute_f0_dio(wav, sampling_rate=sampling_rate, hop_length=hop_length) File "/data/home/gxl/so-vits-svc/utils.py", line 156, in compute_f0_dio import pyworld File "/data/anaconda3/envs/sovits/lib/python3.8/site-packages/pyworld/**init**.py", line 7, in from .pyworld import * File "pyworld/pyworld.pyx", line 6, in init pyworld.pyworld File "**init**.pxd", line 945, in numpy.import_array ImportError: numpy.core.multiarray failed to import

看看numpy版本，如果大于1.22.4的话安装这个版本试试

**Comment by Miuzarte** [comment]
> > 
> 
> 这点常识还是有的，肯定conda activate了
> 
> python preprocess_hubert_f0.py [22] Loading hubert for content... load model(s) from hubert/checkpoint_best_legacy_500.pt INFO:fairseq.tasks.hubert_pretraining:current directory is /data/home/gxl/so-vits-svc INFO:fairseq.tasks.hubert_pretraining:HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False} INFO:fairseq.models.hubert.hubert:HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False} Loaded hubert. 0%| | 0/22 [00:03<?, ?it/s] Process Process-1: Traceback (most recent call last): File "**init**.pxd", line 943, in numpy.import_array RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/data/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/data/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/data/home/gxl/so-vits-svc/preprocess_hubert_f0.py", line 44, in process_batch process_one(filename, hmodel) File "/data/home/gxl/so-vits-svc/preprocess_hubert_f0.py", line 34, in process_one f0 = utils.compute_f0_dio(wav, sampling_rate=sampling_rate, hop_length=hop_length) File "/data/home/gxl/so-vits-svc/utils.py", line 156, in compute_f0_dio import pyworld File "/data/anaconda3/envs/sovits/lib/python3.8/site-packages/pyworld/**init**.py", line 7, in from .pyworld import * File "pyworld/pyworld.pyx", line 6, in init pyworld.pyworld File "**init**.pxd", line 945, in numpy.import_array ImportError: numpy.core.multiarray failed to import

所以解决了吗

**Comment by gak123** [comment]
这个问题我遇到过，你先试试这样：
先卸载numpy,装1.23.5的numpy,之后更新scipy librosa numba,命令应该是pip install -U numba,如果覆盖掉了 就再装一次1.23.5的numpy,这样应该就能解决了

> > 
> 
> 这点常识还是有的，肯定conda activate了
> 
> python preprocess_hubert_f0.py [22] Loading hubert for content... load model(s) from hubert/checkpoint_best_legacy_500.pt INFO:fairseq.tasks.hubert_pretraining:current directory is /data/home/gxl/so-vits-svc INFO:fairseq.tasks.hubert_pretraining:HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False} INFO:fairseq.models.hubert.hubert:HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False} Loaded hubert. 0%| | 0/22 [00:03<?, ?it/s] Process Process-1: Traceback (most recent call last): File "**init**.pxd", line 943, in numpy.import_array RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/data/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/data/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/data/home/gxl/so-vits-svc/preprocess_hubert_f0.py", line 44, in process_batch process_one(filename, hmodel) File "/data/home/gxl/so-vits-svc/preprocess_hubert_f0.py", line 34, in process_one f0 = utils.compute_f0_dio(wav, sampling_rate=sampling_rate, hop_length=hop_length) File "/data/home/gxl/so-vits-svc/utils.py", line 156, in compute_f0_dio import pyworld File "/data/anaconda3/envs/sovits/lib/python3.8/site-packages/pyworld/**init**.py", line 7, in from .pyworld import * File "pyworld/pyworld.pyx", line 6, in init pyworld.pyworld File "**init**.pxd", line 945, in numpy.import_array ImportError: numpy.core.multiarray failed to import

**Comment by dragonyjd** [comment]
> 这个问题我遇到过，你先试试这样： 先卸载numpy,装1.23.5的numpy,之后更新scipy librosa numba,命令应该是pip install -U numba,如果覆盖掉了 就再装一次1.23.5的numpy,这样应该就能解决了
> 
> > > 
> > 
> > 
> > 这点常识还是有的，肯定conda activate了
> > python preprocess_hubert_f0.py [22] Loading hubert for content... load model(s) from hubert/checkpoint_best_legacy_500.pt INFO:fairseq.tasks.hubert_pretraining:current directory is /data/home/gxl/so-vits-svc INFO:fairseq.tasks.hubert_pretraining:HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False} INFO:fairseq.models.hubert.hubert:HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False} Loaded hubert. 0%| | 0/22 [00:03<?, ?it/s] Process Process-1: Traceback (most recent call last): File "**init**.pxd", line 943, in numpy.import_array RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/data/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/data/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/data/home/gxl/so-vits-svc/preprocess_hubert_f0.py", line 44, in process_batch process_one(filename, hmodel) File "/data/home/gxl/so-vits-svc/preprocess_hubert_f0.py", line 34, in process_one f0 = utils.compute_f0_dio(wav, sampling_rate=sampling_rate, hop_length=hop_length) File "/data/home/gxl/so-vits-svc/utils.py", line 156, in compute_f0_dio import pyworld File "/data/anaconda3/envs/sovits/lib/python3.8/site-packages/pyworld/**init**.py", line 7, in from .pyworld import * File "pyworld/pyworld.pyx", line 6, in init pyworld.pyworld File "**init**.pxd", line 945, in numpy.import_array ImportError: numpy.core.multiarray failed to import

太牛了，按你的方法，重装NumPy ==1.23.5，之后pip install -U numba。确定可以训练了，不过一直报下面的警告，告诉 版本太高了，不知道会不会有影响 ？
UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5

**Comment by gak123** [comment]
> 

不会有影响，觉得难受的话直接pip install -U scipy就行

**Comment by gak123** [comment]
> > 这个问题我遇到过，你先试试这样： 先卸载numpy,装1.23.5的numpy,之后更新scipy librosa numba,命令应该是pip install -U numba,如果覆盖掉了 就再装一次1.23.5的numpy,这样应该就能解决了
> > > > 
> > > 
> > > 
> > > 这点常识还是有的，肯定conda activate了
> > > python preprocess_hubert_f0.py [22] Loading hubert for content... load model(s) from hubert/checkpoint_best_legacy_500.pt INFO:fairseq.tasks.hubert_pretraining:current directory is /data/home/gxl/so-vits-svc INFO:fairseq.tasks.hubert_pretraining:HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False} INFO:fairseq.models.hubert.hubert:HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False} Loaded hubert. 0%| | 0/22 [00:03<?, ?it/s] Process Process-1: Traceback (most recent call last): File "**init**.pxd", line 943, in numpy.import_array RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
> > > During handling of the above exception, another exception occurred:
> > > Traceback (most recent call last): File "/data/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/data/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/data/home/gxl/so-vits-svc/preprocess_hubert_f0.py", line 44, in process_batch process_one(filename, hmodel) File "/data/home/gxl/so-vits-svc/preprocess_hubert_f0.py", line 34, in process_one f0 = utils.compute_f0_dio(wav, sampling_rate=sampling_rate, hop_length=hop_length) File "/data/home/gxl/so-vits-svc/utils.py", line 156, in compute_f0_dio import pyworld File "/data/anaconda3/envs/sovits/lib/python3.8/site-packages/pyworld/**init**.py", line 7, in from .pyworld import * File "pyworld/pyworld.pyx", line 6, in init pyworld.pyworld File "**init**.pxd", line 945, in numpy.import_array ImportError: numpy.core.multiarray failed to import
> 
> 太牛了，按你的方法，重装NumPy ==1.23.5，之后pip install -U numba。确定可以训练了，不过一直报下面的警告，告诉 版本太高了，不知道会不会有影响 ？ UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5

不会有影响，觉得难受的话直接pip install -U scipy就行

**Comment by dragonyjd** [comment]
> > > 这个问题我遇到过，你先试试这样： 先卸载numpy,装1.23.5的numpy,之后更新scipy librosa numba,命令应该是pip install -U numba,如果覆盖掉了 就再装一次1.23.5的numpy,这样应该就能解决了
> > > > > 
> > > > 
> > > > 
> > > > 这点常识还是有的，肯定conda activate了
> > > > python preprocess_hubert_f0.py [22] Loading hubert for content... load model(s) from hubert/checkpoint_best_legacy_500.pt INFO:fairseq.tasks.hubert_pretraining:current directory is /data/home/gxl/so-vits-svc INFO:fairseq.tasks.hubert_pretraining:HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': 'metadata', 'fine_tuning': False, 'labels': ['km'], 'label_dir': 'label', 'label_rate': 50.0, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False} INFO:fairseq.models.hubert.hubert:HubertModel Config: {'_name': 'hubert', 'label_rate': 50.0, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'layer_type': transformer, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': True, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False, 'checkpoint_activations': False, 'required_seq_len_multiple': 2, 'depthwise_conv_kernel_size': 31, 'attn_type': '', 'pos_enc_type': 'abs', 'fp16': False} Loaded hubert. 0%| | 0/22 [00:03<?, ?it/s] Process Process-1: Traceback (most recent call last): File "**init**.pxd", line 943, in numpy.import_array RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
> > > > During handling of the above exception, another exception occurred:
> > > > Traceback (most recent call last): File "/data/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/data/anaconda3/envs/sovits/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/data/home/gxl/so-vits-svc/preprocess_hubert_f0.py", line 44, in process_batch process_one(filename, hmodel) File "/data/home/gxl/so-vits-svc/preprocess_hubert_f0.py", line 34, in process_one f0 = utils.compute_f0_dio(wav, sampling_rate=sampling_rate, hop_length=hop_length) File "/data/home/gxl/so-vits-svc/utils.py", line 156, in compute_f0_dio import pyworld File "/data/anaconda3/envs/sovits/lib/python3.8/site-packages/pyworld/**init**.py", line 7, in from .pyworld import * File "pyworld/pyworld.pyx", line 6, in init pyworld.pyworld File "**init**.pxd", line 945, in numpy.import_array ImportError: numpy.core.multiarray failed to import
> > 
> > 
> > 太牛了，按你的方法，重装NumPy ==1.23.5，之后pip install -U numba。确定可以训练了，不过一直报下面的警告，告诉 版本太高了，不知道会不会有影响 ？ UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
> 
> 不会有影响，觉得难受的话直接pip install -U scipy就行

好的，多谢了，现在还一直在跑
