### ISSUE TITLE
在开始推理时显示以下错误，哪位大佬帮帮我。

### ISSUE THREAD

**Issue by Jerryjzr** [svc-develop-team/so-vits-svc#71]
Traceback (most recent call last):
  File "/content/so-vits-svc/inference_main.py", line 128, in <module>
    main()
  File "/content/so-vits-svc/inference_main.py", line 105, in main
    out_audio, out_sr = svc_model.infer(spk, tran, raw_path,
  File "/content/so-vits-svc/inference/infer_tool.py", line 178, in infer
    sid = torch.LongTensor([int(speaker_id)]).to(self.dev).unsqueeze(0)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by njsgdd10086** [comment]
请确保你指定的说话人昵称在config里，或是填写对应的说话人id

**Comment by Jerryjzr** [comment]
> 好的，我去试试，谢谢大佬
