### ISSUE TITLE
[Help]: NotImplementedError: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now ？

### ISSUE THREAD

**Issue by jing5314584** [svc-develop-team/so-vits-svc#82]
### 请勾选下方的确认框。

- [X] 我已仔细阅读README.md。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [x] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

Wondows21H2

### Python版本

3.9.15

### PyTorch版本

1.13.1

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

录制

### 出现问题的环节或执行的命令

训练

### 问题描述

NotImplementedError: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now
是不是环境的问题？

### 日志

```python
(vits) E:\Project\Python\so-vits-svc-4.0>python train.py -c configs/config.json -m 44k
INFO:44k:{'train': {'log_interval': 200, 'eval_interval': 800, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 6, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 102
40, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'use_sr': True, 'max_speclen': 512, 'port': '8001', 'keep_ckpts': 3}, 'data': {'training_files': 'filelists/train.txt', 'validation_files': 'filelists/val.txt', '
max_wav_value': 32768.0, 'sampling_rate': 44100, 'filter_length': 2048, 'hop_length': 256, 'win_length': 2048, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': 22050}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filt
er_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2, 2
], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256, 'ssl_dim': 256, 'n_speakers': 2}, 'spk': {'speaker0': 0, 'speaker1': 1}, 'model_dir':
'./logs\\44k'}
WARNING:44k:E:\Project\Python\so-vits-svc-4.0 is not a git repository, therefore hash value comparison will be ignored.
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
load old checkpoint failed...
Traceback (most recent call last):
  File "E:\Project\Python\so-vits-svc-4.0\train.py", line 312, in <module>
    main()
  File "E:\Project\Python\so-vits-svc-4.0\train.py", line 53, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes
    while not context.join():
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "E:\Project\Python\so-vits-svc-4.0\train.py", line 121, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "E:\Project\Python\so-vits-svc-4.0\train.py", line 143, in train_and_evaluate
    for batch_idx, items in enumerate(train_loader):
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
NotImplementedError: Caught NotImplementedError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\ProgramData\Anaconda3\envs\vits\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Project\Python\so-vits-svc-4.0\data_utils.py", line 88, in __getitem__
    return self.get_audio(self.audiopaths[index][0])
  File "E:\Project\Python\so-vits-svc-4.0\data_utils.py", line 53, in get_audio
    spec = spectrogram_torch(audio_norm, self.filter_length,
  File "E:\Project\Python\so-vits-svc-4.0\modules\mel_processing.py", line 63, in spectrogram_torch
    y = F.pad(y.unsqueeze(1), (int((n_fft-hop_size)/2), int((n_fft-hop_size)/2)), mode='reflect')
NotImplementedError: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now
```

### 截图`so-vits-svc`文件夹并粘贴到此处

![image](https://user-images.githubusercontent.com/13688884/227427111-f4314f15-fdfa-43ec-99c4-91951d7f2ef0.png)

**Comment by Miuzarte** [comment]
截图一下logs/44k文件夹，是不是用的底模不匹配这个分支

**Comment by jing5314584** [comment]
![image](https://user-images.githubusercontent.com/13688884/227429871-e6e4df0d-9c4b-4c6b-8d01-3a038f114801.png)

**Comment by Miuzarte** [comment]
> ![image](https://user-images.githubusercontent.com/13688884/227429871-e6e4df0d-9c4b-4c6b-8d01-3a038f114801.png)

先尝试移走底模开始训练看看能不能开始训练，能的话排除环境问题
然后用4.0-v2这个分支带着这个底模训练试试，可能这个是4.0-v2的底模，训练集需要重新生成配置文件`python preprocess_flist_config.py`

**Comment by jing5314584** [comment]
移除底模还是同样的问题
![image](https://user-images.githubusercontent.com/13688884/227431073-ae078a8a-eb8c-4570-b275-95f0aa47e65e.png)

**Comment by leng-yue** [comment]
我感觉是你数据集有空音频之类的东西... 你尝试在这里 print 下 y 的 shape?

**Comment by jing5314584** [comment]
![image](https://user-images.githubusercontent.com/13688884/227433242-0585cfa6-7fb8-4a66-8994-02ccd2d15d61.png)

**Comment by leng-yue** [comment]
从这个 size 来看, 你的输入音频是双声道的. 你运行了 resample.py 么

**Comment by jing5314584** [comment]
运行了
![image](https://user-images.githubusercontent.com/13688884/227434487-6f6d953a-09be-4f6b-b596-243f0f57ab87.png)

**Comment by leng-yue** [comment]
你把你数据拉进 au 看看.

**Comment by jing5314584** [comment]
[speaker0.zip](https://github.com/svc-develop-team/so-vits-svc/files/11058833/speaker0.zip)

**Comment by leng-yue** [comment]
我在本地测了下, 没有遇到你发的报错. 你自己拿这几个样本试试?

**Comment by jing5314584** [comment]
好像是音频的问题  我把音频就剩这几个了 就可以跑了

**Comment by fish5257** [comment]
-- Process 0 terminated with the following error:             
这段打印我训练时遇到过，但没遇到下面那段。
当时问题是训练集当中有部分音频过大或者过长.有几个5mb的音频，时长30s+，后面我把这几个问题音频再切小了点就能训练了。

**Comment by NaruseMioShirakana** [comment]
DataLoader的报错都是数据集数据的问题或者预处理的问题，检查你的数据集数据是否符合要求
