### ISSUE TITLE
[Help]: 在训练时运行    python train.py -c configs/config.json -m 32k后显示CUDA out of memory. Tried to allocate 28.00 MiB

### ISSUE THREAD

**Issue by fusheng111** [svc-develop-team/so-vits-svc#84]
### 请勾选下方的确认框。

- [X] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

windows11 22h2

### Python版本

 3.10.10

### PyTorch版本

 1.13.0+cu117

### sovits分支

3.0-32k

### 数据集来源（用于判断数据集质量）

游戏内录制

### 出现问题的环节或执行的命令

训练

### 问题描述

在训练时运行    
python train.py -c configs/config.json -m 32k
显示
CUDA out of memory. Tried to allocate 28.00 MiB

### 日志

```python
PS E:\TOOL\aiv\so-vits-svc-3.0-32k>     python train.py -c configs/config.json -m 32k
INFO:32k:{'train': {'log_interval': 200, 'eval_interval': 1000, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 12, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 17920, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'use_sr': True, 'max_speclen': 384, 'port': '8001', 'keep_ckpts': 5}, 'data': {'training_files': 'filelists/train.txt', 'validation_files': 'filelists/val.txt', 'max_wav_value': 32768.0, 'sampling_rate': 32000, 'filter_length': 1280, 'hop_length': 320, 'win_length': 1280, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256, 'ssl_dim': 256, 'n_speakers': 2}, 'spk': {'tressa': 0}, 'model_dir': './logs\\32k'}
WARNING:32k:E:\TOOL\aiv\so-vits-svc-3.0-32k is not a git repository, therefore hash value comparison will be ignored.
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
./logs\32k\G_0.pth
INFO:32k:emb_g.weight is not in the checkpoint
INFO:32k:Loaded checkpoint './logs\32k\G_0.pth' (iteration 1)
./logs\32k\D_0.pth
INFO:32k:Loaded checkpoint './logs\32k\D_0.pth' (iteration 1)
Traceback (most recent call last):
  File "E:\TOOL\aiv\so-vits-svc-3.0-32k\train.py", line 288, in <module>
    main()
  File "E:\TOOL\aiv\so-vits-svc-3.0-32k\train.py", line 48, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "C:\Users\NAVY\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "C:\Users\NAVY\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes
    while not context.join():
  File "C:\Users\NAVY\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\NAVY\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "E:\TOOL\aiv\so-vits-svc-3.0-32k\train.py", line 109, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "E:\TOOL\aiv\so-vits-svc-3.0-32k\train.py", line 147, in train_and_evaluate
    (z, z_p, m_p, logs_p, m_q, logs_q) = net_g(c, f0, spec, g=g, mel=mel)
  File "C:\Users\NAVY\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\NAVY\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\parallel\distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "C:\Users\NAVY\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\parallel\distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "C:\Users\NAVY\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\TOOL\aiv\so-vits-svc-3.0-32k\models.py", line 337, in forward
    o = self.dec(z_slice, g=g, f0=pitch_slice)
  File "C:\Users\NAVY\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\TOOL\aiv\so-vits-svc-3.0-32k\vdecoder\hifigan\models.py", line 334, in forward
    xs += self.resblocks[i * self.num_kernels + j](x)
  File "C:\Users\NAVY\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\TOOL\aiv\so-vits-svc-3.0-32k\vdecoder\hifigan\models.py", line 64, in forward
    x = xt + x
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 28.00 MiB (GPU 0; 6.00 GiB total capacity; 5.18 GiB already allocated; 0 bytes free; 5.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

PS E:\TOOL\aiv\so-vits-svc-3.0-32k>
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

![image](https://user-images.githubusercontent.com/65170715/227532740-2e5998d8-b5a4-449e-a9e2-2bb93d6deaac.png)
![image](https://user-images.githubusercontent.com/65170715/227532748-c9218e93-7233-4180-a6b7-a2c5d1d281d7.png)

**Comment by seq2193** [comment]
wav 切片 60秒一段

#@title raw目录音频切片器（遇到CUDA错误时需要切片再推理）
!pip install pydub
import os
from pydub import AudioSegment

# 定义输入和输出目录
input_dir = "/content/so-vits-svc/raw"
output_dir = "/content/so-vits-svc/raw"

# 遍历输入目录中的所有音频文件
for file_name in os.listdir(input_dir):
    # 仅处理扩展名为 wav 的文件
    if file_name.endswith(".wav"):
        # 加载音频文件
        audio = AudioSegment.from_file(os.path.join(input_dir, file_name), format="wav")
        
        # 计算每60秒的毫秒数
        segment_length_ms = 60 * 1000
        
        # 切割音频文件
        segments = []
        for start_time in range(0, len(audio), segment_length_ms):
            end_time = start_time + segment_length_ms
            segment = audio[start_time:end_time]
            segments.append(segment)
        
        # 保存切割后的音频文件到输出目录
        for i, segment in enumerate(segments):
            output_file_name = f"{os.path.splitext(file_name)[0]}_{i}.wav"
            output_path = os.path.join(output_dir, output_file_name)
            segment.export(output_path, format="wav")

**Comment by Miuzarte** [comment]
> 

没有必要回复这种stupid issue

**Comment by HuanLinOTO** [comment]
你的问题是切片时间过长，一般推荐能切多短就多短，如果还是有问题，请提供你的显卡信息并 reopen 此 issue，感谢你对 sovits 项目的支持
