### ISSUE TITLE
进行聚类方案训练时出现错误

### ISSUE THREAD

**Issue by Jerryjzr** [svc-develop-team/so-vits-svc#92]
root@autodl-container-ecb6118152-031fe729:~/autodl-tmp/so-vits-svc# python cluster/train_cluster.py
train kmeans for moss...
INFO:__main__:Loading features from dataset/44k/moss
20it [00:00, 1820.13it/s]
0 7.01171875 MB , shape: (7180, 256) float32
INFO:__main__:Clustering features of shape: (7180, 256)
Traceback (most recent call last):
  File "cluster/train_cluster.py", line 64, in <module>
    x = train_cluster(in_dir, n_clusters, verbose=False)
  File "cluster/train_cluster.py", line 30, in train_cluster
    kmeans = MiniBatchKMeans(n_clusters=n_clusters,verbose=verbose, batch_size=4096, max_iter=80).fit(features)
  File "/root/miniconda3/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line 1972, in fit
    self._check_params(X)
  File "/root/miniconda3/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line 1804, in _check_params
    super()._check_params(X)
  File "/root/miniconda3/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line 828, in _check_params
    raise ValueError(
ValueError: n_samples=7180 should be >= n_clusters=10000.
root@autodl-container-ecb6118152-031fe729:~/autodl-tmp/so-vits-svc#

**Comment by Jerryjzr** [comment]
请问如何解决训练步速应该是达到标准了把？
![image](https://user-images.githubusercontent.com/94814348/227814086-a541ffcf-e58b-458a-b4eb-1bf6bdaa31ee.png)

**Comment by Jerryjzr** [comment]
> 
root@autodl-container-ecb6118152-031fe729:~/autodl-tmp/so-vits-svc# python cluster/train_cluster.py
train kmeans for moss...
INFO:__main__:Loading features from dataset/44k/moss
20it [00:00, 1820.13it/s]
0 7.01171875 MB , shape: (7180, 256) float32
INFO:__main__:Clustering features of shape: (7180, 256)
Traceback (most recent call last):
  File "cluster/train_cluster.py", line 64, in <module>
    x = train_cluster(in_dir, n_clusters, verbose=False)
  File "cluster/train_cluster.py", line 30, in train_cluster
    kmeans = MiniBatchKMeans(n_clusters=n_clusters,verbose=verbose, batch_size=4096, max_iter=80).fit(features)
  File "/root/miniconda3/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line 1972, in fit
    self._check_params(X)
  File "/root/miniconda3/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line 1804, in _check_params
    super()._check_params(X)
  File "/root/miniconda3/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line 828, in _check_params
    raise ValueError(
ValueError: n_samples=7180 should be >= n_clusters=10000.

**Comment by Jerryjzr** [comment]
解决了，把train_cluster.py文件内 n_clusters=10000参数改为了7180。可能是我的数据太少了吧
