### ISSUE TITLE
[Help]: Error when train more thank one speaker

### ISSUE THREAD

**Issue by crankyz** [svc-develop-team/so-vits-svc#96]
### Please check the checkboxes below.

- [X] I have read *[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README.md)* and *[Quick solution in wiki](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)* carefully.
- [X] I have been troubleshooting issues through various search engines. The questions I want to ask are not common.
- [X] I am NOT using one click package / environment package.

### OS version

Win 10 

### GPU

2x1080ti

### Python version

3.8.6

### PyTorch version

1.13.1

### Branch of sovits

4.0(Default)

### Dataset source (Used to judge the dataset quality)

Dosent matter

### Where thr problem occurs or what command you executed

python train.py -c configs/config.json -m 44k

### Problem description

Work normally if one speaker in a dataset, but when more than one got this error "RuntimeError: output with shape [1, 256] doesn't match the broadcast shape [2, 256]" and in this particular error 2 mean 2 speakers.

### Log

```python
C:\Users\ritabri\.conda\envs\svc_train\lib\site-packages\torch\autograd\__init__.py:197: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [32, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [32, 1, 4], strides() = [4, 4, 1] (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\reducer.cpp:339.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
C:\Users\ritabri\.conda\envs\svc_train\lib\site-packages\torch\autograd\__init__.py:197: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [32, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [32, 1, 4], strides() = [4, 4, 1] (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\distributed\c10d\reducer.cpp:339.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "train.py", line 312, in <module>
    main()
  File "train.py", line 53, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "C:\Users\ritabri\.conda\envs\svc_train\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "C:\Users\ritabri\.conda\envs\svc_train\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes
    while not context.join():
  File "C:\Users\ritabri\.conda\envs\svc_train\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\ritabri\.conda\envs\svc_train\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "D:\so-vits-svc\train.py", line 124, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "D:\so-vits-svc\train.py", line 204, in train_and_evaluate
    scaler.step(optim_g)
  File "C:\Users\ritabri\.conda\envs\svc_train\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 313, in step
    return optimizer.step(*args, **kwargs)
  File "C:\Users\ritabri\.conda\envs\svc_train\lib\site-packages\torch\optim\lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\ritabri\.conda\envs\svc_train\lib\site-packages\torch\optim\optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\ritabri\.conda\envs\svc_train\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ritabri\.conda\envs\svc_train\lib\site-packages\torch\optim\adamw.py", line 162, in step
    adamw(params_with_grad,
  File "C:\Users\ritabri\.conda\envs\svc_train\lib\site-packages\torch\optim\adamw.py", line 219, in adamw
    func(params,
  File "C:\Users\ritabri\.conda\envs\svc_train\lib\site-packages\torch\optim\adamw.py", line 273, in _single_tensor_adamw
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: output with shape [1, 256] doesn't match the broadcast shape [2, 256]
```

### Screenshot `so-vits-svc` and `logs/44k` folders and paste here

![image](https://user-images.githubusercontent.com/38855421/227970121-ddb0dbcc-728d-442f-80bd-3effd1f7d234.png)
![image](https://user-images.githubusercontent.com/38855421/227970535-fe49ce93-7f93-4ee5-889a-1d71cfdb376a.png)

**Comment by NaruseMioShirakana** [comment]
The pre-trained model you use may be one that does not remove the speaker embidding weight (a pre-trained model that has already been used by someone else).
This can be done by either removing the speaker embidding weight of the pre-trained model or setting the n_speaker of config to the first element in broadcast shape [2, 256], in this case 2

**Comment by crankyz** [comment]
"removing the speaker embidding weight of the pre-trained model" How to do that? In config its ofcourse n_speaker same number as folders in a dataset. "The pre-trained model you use may be one that does not remove the speaker embidding weight" Do u mean G_0 and D_0? Thank you for answers anyway.

**Comment by crankyz** [comment]
Downloaded another G_0 and D_0, and works perfectly now.
